version: '3'

services:
  app:
    image: sem3bank:latest
    build: 
      context: .
    container_name: app
    networks: 
      - sem3bank-network
    volumes: 
      - ./sem3bank:/usr/src/app
    tty: true
    environment: 
      - spring.datasource.url=jdbc:mysql://db:3306/sem3bank
      - spring.datasource.username=root
      - spring.datasource.password=tomateseco
      - spring.jpa.show-sql=true
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL57Dialect
      - spring.jpa.hibernate.ddl-auto=update
      - JWT_SECRET=secret
      - FILEIO_API_URL=https://file.io
      - FILEIO_API_KEY=BEOHMYC.NA1Y16K-H63MWJ2-N331FYM-JYZQSFA

    depends_on:
      - db
    ports: 
      - "8080:8080"

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment: 
      - MYSQL_DATABASE=sem3bank
      - MYSQL_ROOT_PASSWORD=tomateseco
    networks: 
      - sem3bank-network

volumes:
  mysql:

networks:
  sem3bank-network:
    driver: bridge
