name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build .war
      run: |
        ./mvnw clean package
      working-directory: ../

    - name: Set up Docker
      uses: docker/setup-action@v2

    - name: Build Docker image
      run: |
        docker build -t sem3bank:latest .
      working-directory: ../

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to Docker Hub
      run: |
        # Configure e faça o push da sua imagem Docker para um registro (por exemplo, Docker Hub)
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push sem3bank
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
