name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Sem3Bank

    env:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/sem3bank
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: tomateseco
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL57Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: secret
      FILEIO_API_URL: https://file.io

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2.3.1
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Wait for MySQL to be ready
      run: |
        for i in {1..60}; do
          if nc -z db 3306; then
            echo "MySQL is ready."
            break
          fi
          echo "Waiting for MySQL to be ready (attempt $i)..."
          sleep 1
        done

    - name: Build .war
      run: |
        # Coloque aqui os comandos para construir o projeto .war
        mvn clean package
      working-directory: .

    - name: Debug Database Connection
      run: |
        echo "Attempting to connect to the database..."
        mysql -h db -u $SPRING_DATASOURCE_USERNAME -p$SPRING_DATASOURCE_PASSWORD -e "SELECT 1"
        echo "Connected to the database successfully."
      env:
        SPRING_DATASOURCE_USERNAME: $SPRING_DATASOURCE_USERNAME
        SPRING_DATASOURCE_PASSWORD: $SPRING_DATASOURCE_PASSWORD

    - name: Build and push Docker image
      run: |
        docker build -t Sem3Bank:latest -f .
        docker tag Sem3Bank:latest whelytom/Sem3Bank:latest
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push whelytom/Sem3Bank:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
