name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Sem3Bank

    env:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/sem3bank
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: tomateseco
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL57Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: secret
      FILEIO_API_URL: https://file.io

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2.3.1
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Build .war
      run: |
        # Coloque aqui os comandos para construir o projeto .war
        mvn clean package -Dmaven.test.skip=true
      working-directory: .

    - name: Build and push Docker image
      run: |
        docker build -t Sem3Bank:latest -f .  # O contexto de construção é definido como o diretório atual (raiz do projeto)
        docker tag Sem3Bank:latest whelytom/Sem3Bank:latest
        echo whelytom | docker login -u whelytom --password-stdin
        docker push whelytom/Sem3Bank:latest
