name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build .war
      run: |
        # Coloque aqui os comandos para construir o projeto .war
        cd ../../
        ./mvn clean package
      working-directory: .

    - name: Build and push Docker image
      run: |
        docker build -t Sem3Bank:latest -f .
        docker tag Sem3Bank:latest whelytom/Sem3Bank:latest
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push whelytom/Sem3Bank:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
